recipe: default.v1
language: en
assistant_id: rasa-calm-hybrid-demo

pipeline:
- name: CompactLLMCommandGenerator
  prompt_template: custom/command_prompt_gpt_4o_template.jinja2
  llm:
    model_group: openai-gpt-4o

#pipeline:
#  - name: CompactLLMCommandGenerator
#    prompt: custom/command_prompt_gpt_4o_template.jinja2
#    llm:
#      model_name: gpt-4o-2024-11-20
#      provider: openai

policies:
- name: FlowPolicy


#recipe: default.v1
#language: en
#pipeline:
#- name: WhitespaceTokenizer
#- name: LanguageModelFeaturizer
#  model_name: "bert"
#  model_weights: "sentence-transformers/all-MiniLM-L6-v2"
#- name: "CRFEntityExtractor"
#- name: LexicalSyntacticFeaturizer
#- name: CountVectorsFeaturizer
#- name: LogisticRegressionClassifier
#- name: EntitySynonymMapper
##- name: DucklingEntityExtractor
##  # url of the running duckling server
##  url: "http://0.0.0.0:8000"
##  dimensions: ["time", "number", "amount-of-money", "distance", "email"]
##  locale: "en_US"
##  timezone: "US/Eastern"
##  timeout : 3
#- name: NLUCommandAdapter
#
#policies:
#- name: FlowPolicy



